baseURL = 'https://example.org/'
languageCode = 'ru-ru'
title = 'Мой проект'
theme = "ananke"
[params]
  primary_color = "#3a5a78"
  [menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Журнал"
    url = "/journal/"
    weight = 2
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 4
  [[menu.main]]
    name = "Участники"
    url = "/team/"
    weight = 5